buildscript {
    ext{
        springBootVersion = '4.1.0'
        springCouldVersion = '2025.1.0'
    }
    repositories {
        mavenLocal()
        mavenCentral()
        maven {
            url "https://plugins.gradle.org/m2/"
        }
    }
    dependencies{
        classpath("org.springframework.boot:spring-boot-gradle-plugin:${springBootVersion}")
        classpath("io.spring.gradle:dependency-management-plugin:1.0.11.RELEASE")
    }
}

allprojects {
    group 'play.with.integration'
}

subprojects {
    apply plugin: 'java'
    apply plugin: 'idea'
    apply plugin: 'maven-publish'
    apply plugin: 'io.spring.dependency-management'
    apply plugin: 'org.springframework.boot'

    java {
        sourceCompatibility = JavaVersion.VERSION_25
        targetCompatibility = JavaVersion.VERSION_25
    }

    repositories {
        mavenCentral()
    }

    test {
        useJUnitPlatform()
    }

    task listAllDependencies {
        doLast {
            configurations.each { config ->
                if (config.isCanBeResolved()) {
                    println "Dependencies for ${config.name}:"
                    config.resolvedConfiguration.resolvedArtifacts.each { artifact ->
                        println "  ${artifact.moduleVersion.id}"
                    }
                }
            }
        }
    }
}