spring:
  application:
    name: SpringIntegrationHelloWorld

flow:
  pollingFrequency: "4000"
  inputDirectory: app-input
  failedDirectory: app-failed
  invalidDirectory: app-invalid
  processedDirectory: app-processed
batch:
  jobName: SpringBatchJob
  stepName: StepOne
  chunkSize: 1000
  endpoint: https://httpbin.org/get