spring:
  application:
    name: SpringIntegrationHelloWorld

flow:
  inboundDirectory: app-input
  filteredDirectory: app-filtered
  failedDirectory: app-failed
  rejectedDirectory: app-rejected
  processedDirectory: app-processed
  pollingFrequency: "4000"
batch:
  jobName: SpringBatchJob
  stepName: StepOne
  chunkSize: 1000