dependencyManagement{
    imports{
        mavenBom "org.springframework.cloud:spring-cloud-dependencies:${springCouldVersion}"
    }
}
dependencies {
    implementation('org.springframework.boot:spring-boot-starter-integration')
    implementation('org.springframework.boot:spring-boot-starter-web')
    implementation('org.springframework.boot:spring-boot-starter-batch')
    implementation 'org.springframework.batch:spring-batch-integration'
    implementation 'org.springframework.integration:spring-integration-file'
    implementation 'com.fasterxml.jackson.core:jackson-databind'
    compileOnly "org.projectlombok:lombok:1.18.42"
    annotationProcessor "org.projectlombok:lombok:1.18.42"
}